# Generated by Django 5.1.5 on 2025-03-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_topic_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(default='f2de31d0-92be-4974-8a13-4f4790508f18', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.topic'),
            preserve_default=False,
        ),
    ]
