# Generated by Django 5.1.5 on 2025-03-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.topic', to_field='topic_id'),
        ),
    ]
